### ISSUE TITLE
breaks with Module::CPANfile 1.1003

### ISSUE THREAD

**Issue by miyagawa** [charsbar/Perl-PrereqScanner-NotQuiteLite#1]
https://rt.cpan.org/Public/Bug/Display.html?id=125190

... because this module subclasses and messes with the internals, which i just changed.

Please make a feature request or PR against Module::CPANfile so that you don't need to do that.

**Comment by charsbar** [comment]
Had a plan to do so but unfortunately didn't have time. Sent a PR to fix a issue. Will do a few more later. For now PPSNQL 0.92 should work with Module::CPANfile 1.1003.
